name: CI

on:
  pull_request:
    branches: [main]

jobs:
  perform_overlay_and_cache:
    name: Overlay Base Software and Cache
    uses: ./.github/workflows/overlay_software_and_cache.yml
  perform_ci:
    name: Perform CI
    needs: perform_overlay_and_cache
    ## GitHub currently does not support evaluating expressions
    # uses: waggle-sensor/wildnode-image/blob/main/.github/workflows/ci.yml@${{ needs.run_base_image_tag_collector.outputs.base_image_tag }}
    uses: waggle-sensor/wildnode-image/.github/workflows/ci.yml@main
    secrets: inherit
    with:
      overlay_cache_key: ${{ needs.perform_overlay_and_cache.outputs.overlay_cache_key }}
