name: Collect Base Image Tag

on:
  workflow_call:
    outputs:
      base_image_tag:
        description: "The base image tag to use for reusable workflows"
        value: ${{ jobs.collect_base_image_tag.outputs.version }}

jobs:
  collect_base_image_tag:
    name: Collect and Output Base Image Tag
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.baseversion.outputs.stepversion }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read Base Version
        id: baseversion
        run: |
          echo "::set-output name=stepversion::$(cat base_image_tag | xargs)"
          cat base_image_tag | xargs
