name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  run_base_image_tag_collector:
    uses: ./.github/workflows/collect_base_image_tag.yml
  build_release:
    name: Build and Create Release
    runs-on: ubuntu-latest
    needs: run_base_image_tag_collector
    steps:
      - uses: waggle-sensor/wildnode-image/blob/main/.github/workflows/release.yml@${{ needs.run_base_image_tag_collector.outputs.version }}
