name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  run_base_image_tag_collector:
    name: "Base Image Tag Collection"
    uses: ./.github/workflows/collect_base_image_tag.yml
  create_release:
    needs: run_base_image_tag_collector
    ## GitHub currently does not support evaluating expressions
    # uses: waggle-sensor/wildnode-image/blob/main/.github/workflows/release.yml@${{ needs.run_base_image_tag_collector.outputs.base_image_tag }}
    uses: waggle-sensor/wildnode-image/.github/workflows/release.yml@main
    secrets: inherit
